name: Flutter iOS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS App
        run: flutter build ios --release

      - name: Archive iOS App
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          mkdir -p $HOME/outputs/ipa
          cp build/ios/iphoneos/Runner.app/Info.plist $HOME/outputs/ipa/
          cp build/ios/iphoneos/Runner.app/Runner $HOME/outputs/ipa/
          cd $HOME/outputs/ipa
          zip -r app.ipa Info.plist Runner
