name: Flutter iOS Deployment

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get
        
      - name: Cache Dependencies
        uses: actions/cache@v4.0.2
        with:
          cd ../
        run: mkdir -p /.pub-cache
        path: ~/.pub-cache
          
      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Create IPA and .app
        run: |
          mkdir -p $HOME/outputs/ipa
          cp -R build/ios/iphoneos/Runner.app $HOME/outputs/ipa/
          cd $HOME/outputs/ipa
          zip -r app.ipa Runner.app
          
      - name: Cache Artifacts
        uses: actions/cache@v2
        with:
          path: $HOME/outputs/ipa

              artifacts:
          - build/ios/iphoneos/Runner.app
          - $HOME/outputs/ipa
          - /tmp/xcodebuild_logs/*.log
          - flutter_drive.log
          - build/ios/iphoneos

      publishing: 
      email:
        recipients:
          - realperkypimp@gmail.com
        notify:
          success: true
          failure: false
