name: Flutter iOS Deployment

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Create IPA and .app
        run: |
          mkdir -p $HOME/outputs/ipa
          cp -R build/ios/iphoneos/Runner.app $HOME/outputs/ipa/
          cd $HOME/outputs/ipa
          zip -r app.ipa Runner.app
          
      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS App
          path: $HOME/outputs/ipa/app.ipa

  download:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: iOS App
          path: artifacts
