name: Flutter iOS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:

      - name: Set Up Flutter
        uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Create IPA and .app
        run: |
          mkdir -p $HOME/outputs/ipa
          cp -R build/ios/iphoneos/Runner.app $HOME/outputs/ipa/
          cd $HOME/outputs/ipa
          zip -r app.ipa Runner.app

      - name: Cache Artifacts
        uses: actions/cache@v2
        with:
          path: |
            build/ios/iphoneos/Runner.app
            $HOME/outputs/ipa
            /tmp/xcodebuild_logs/*.log
            flutter_drive.log
            build/ios/iphoneos

      - name: Publish Artifacts
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: kthnxlol@gmail.com 
          password: '@c1dr0cks'
          subject: "Build Artifacts"
          body: "The build artifacts are attached."
          attachments: |
            $HOME/outputs/ipa/app.ipa
            build/ios/iphoneos/Runner.app
            /tmp/xcodebuild_logs/*.log
            flutter_drive.log

      - name: Release Upload
        uses: d1ceward/draft-assets-release-action@v2.1.0
        with:
          token: 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
          files: |
            $HOME/outputs/ipa/app.ipa
            build/ios/iphoneos/Runner.app
            /tmp/xcodebuild_logs/*.log
            flutter_drive.log
