name: Flutter iOS Deployment

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get
        
      - name: Cache Dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ~/.pub-cache
          key: flutter-pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Create IPA and .app
        run: |
          mkdir -p $HOME/outputs/ipa
          cp -R build/ios/iphoneos/Runner.app $HOME/outputs/ipa/
          cd $HOME/outputs/ipa
          zip -r app.ipa Runner.app
      - name: Cache Artifacts
        uses: actions/cache@v2
        with:
          path: $HOME/outputs/ipa
          key: flutter-artifacts-${{ runner.os }}-${{ hashFiles('**/Runner.app') }}

      - name: Cache
        uses: actions/cache@v4.0.2
        with:
    # A list of files, directories, and wildcard patterns to cache and restore
          path: $HOME/outputs/ipa/
    # An explicit key for restoring and saving the cache
          key: 542356654
    # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
          enableCrossOsArchive: true
          fail-on-cache-miss: true
          save-always: true
          
