name: Flutter iOS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Cache Dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ~/.pub-cache
          key: flutter-pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Create IPA and .app
        run: |
          flutter build ios --release --no-codesign
          mkdir -p $HOME/outputs/ipa
          cp -R build/ios/iphoneos/Runner.app $HOME/outputs/ipa/
          cd $HOME/outputs/ipa
          zip -r app.ipa Runner.app
          cp -R pwd /Users/runner/work/CashyClone/CashyClone/build/ios/iphoneos/Runner.app /Users/shloppytop/CashyClone/
      
      - uses: actions/download-artifact@v4
        with:
          repository: shloppytop/CashyClone
          github-token: ${{ secrets.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 }}
          path: /ios

      - name: Display structure of downloaded files
        run: ls -R

