name: Xcode - Build, Archive, and Export

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, Archive, and Export iOS app
    runs-on: macos-latest

    steps:
      - name: Set Scheme
        run: |
          scheme="/Users/runner/work/CashyClone/CashyClone/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme"
          echo "Scheme Location: $scheme"

      - name: Build
        env:
          scheme: "$scheme"
        run: |
          cd ~ ~
          cd /Users/runner/work/CashyClone/ios/Runner.xcodeproj/project.xcworkspace/
          xcodebuild clean build analyze \
            -workspace "contents.xcworkspacedata" \
            -scheme "$scheme" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Archive
        run: |
          cd /ios
          xcodebuild archive \
            -workspace "project.xcworkspace" \
            -scheme "$scheme" \
            -archivePath "build/Runner.xcarchive" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Export IPA
        run: |
          cd /Users/runner/work/CashyClone/CashyClone/ios
          xcodebuild -exportArchive \
            -archivePath "build/Runner.xcarchive" \
            -exportOptionsPlist "exportOptions.plist" \
            -exportPath "build" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS App
          path: /Users/runner/work/CashyClone/CashyClone/ios/build/Runner.ipa
