name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze iOS app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Default Scheme
        run: |
          cd /Users/runner/work/CashyClone/CashyClone/ios/Runner.xcodeproj/xcshareddata/xcschemes
          default=$(basename Runner.xcscheme .xcscheme)
          echo $default > default
          echo "Using default scheme: $default"

      - name: Build
        env:
          scheme: ${{ steps.set_default.outputs.default_scheme }}
        run: |
          cd /Users/runner/work/CashyClone/CashyClone/ios/Runner.xcodeproj/
          xcodebuild clean build analyze \
            -workspace "Runner.xcworkspace" \
            -scheme "$scheme" \
            | xcpretty && exit ${PIPESTATUS[0]}
