name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'ios/Runner.xcodeproj/project.xcworkspace'
      - name: Set Default Scheme
        run: |
          scheme_file="ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme"
          workspace_file="ios/Runner.xcodeproj/project.xcworkspace"
          default=$(basename "$scheme_file" .xcscheme)
          echo $default | cat > default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ -d "$PWD/$workspace_file" ]; then
            filetype_parameter="workspace"
            file_to_build="$PWD/$workspace_file"
          else
            filetype_parameter="project"
            file_to_build="$PWD/$scheme_file"
          fi
          file_to_build=$(echo "$file_to_build" | awk '{$1=$1;print}')
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
