name: Xcode - Build, Archive, and Export

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, Archive, and Export iOS app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Default Scheme
        run: |
          cd /Users/runner/work/CashyClone/CashyClone/ios/Runner.xcodeproj/xcshareddata/xcschemes
          default=$(basename Runner.xcscheme)
          echo $default > default
          echo "Using default scheme: $default"

      - name: Build
        env:
          scheme: ${{ steps.set_default.outputs.default_scheme }}
        run: |
          cd /Users/runner/work/CashyClone/CashyClone/ios/Runner.xcodeproj
          xcodebuild clean build analyze \
            -workspace "project.xcworkspace" \
            -scheme "default" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Archive
        run: |
          cd /Users/runner/work/CashyClone/CashyClone/ios
          xcodebuild archive \
            -workspace "project.xcworkspace" \
            -scheme "$scheme" \
            -archivePath "build/Runner.xcarchive" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Export IPA
        run: |
          cd /Users/runner/work/CashyClone/CashyClone/ios
          xcodebuild -exportArchive \
            -archivePath "build/Runner.xcarchive" \
            -exportOptionsPlist "exportOptions.plist" \
            -exportPath "build" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS App
          path: /Users/runner/work/CashyClone/CashyClone/ios/build/Runner.ipa
